library(tidyverse)

D <- read.csv('/Users/tom/Git/ecmtool/conversion_cone.csv', header = FALSE)
colnames(D) <- c("3-Phospho-D-glyceroyl phosphate", "D-Glycerate 2-phosphate", "3-Phospho-D-glycerate", "6-Phospho-D-gluconate", "6-phospho-D-glucono-1,5-lactone", "Acetate", "Acetate", "Acetaldehyde", "Acetaldehyde", "Acetyl-CoA", "Cis-Aconitate", "Acetyl phosphate", "ADP C10H12N5O10P2", "2-Oxoglutarate", "2-Oxoglutarate", "AMP C10H12N5O7P", "ATP C10H12N5O13P3", "Citrate", "CO2 CO2", "CO2 CO2", "Coenzyme A", "Dihydroxyacetone phosphate", "D-Erythrose 4-phosphate", "Ethanol", "Ethanol", "D-Fructose 6-phosphate", "D-Fructose 1,6-bisphosphate", "Formate", "Formate", "D-Fructose", "Fumarate", "Fumarate", "Glyceraldehyde 3-phosphate", "D-Glucose 6-phosphate", "D-Glucose", "L-Glutamine", "L-Glutamine", "L-Glutamate", "L-Glutamate", "Glyoxylate", "H2O H2O", "H2O H2O", "H+", "H+", "Isocitrate", "D-Lactate", "D-Lactate", "L-Malate", "L-Malate", "Nicotinamide adenine dinucleotide", "Nicotinamide adenine dinucleotide - reduced", "Nicotinamide adenine dinucleotide phosphate", "Nicotinamide adenine dinucleotide phosphate - reduced", "Ammonium", "Ammonium", "O2 O2", "O2 O2", "Oxaloacetate", "Phosphoenolpyruvate", "Phosphate", "Phosphate", "Pyruvate", "Pyruvate", "Ubiquinone-8", "Ubiquinol-8", "Alpha-D-Ribose 5-phosphate", "D-Ribulose 5-phosphate", "Sedoheptulose 7-phosphate", "Succinate", "Succinate", "Succinyl-CoA", "D-Xylulose 5-phosphate", "Virtual objective metabolite")
#colnames(D) <- c("3-Phospho-D-glyceroyl phosphate", "D-Glycerate 2-phosphate", "3-Phospho-D-glycerate", "6-Phospho-D-gluconate", "6-phospho-D-glucono-1,5-lactone", "Acetate", "Acetate", "Acetaldehyde", "Acetaldehyde", "Acetyl-CoA", "Cis-Aconitate", "Acetyl phosphate", "ADP C10H12N5O10P2", "2-Oxoglutarate", "2-Oxoglutarate", "AMP C10H12N5O7P", "ATP C10H12N5O13P3", "Citrate", "CO2 CO2", "CO2 CO2", "Coenzyme A", "Dihydroxyacetone phosphate", "D-Erythrose 4-phosphate", "Ethanol", "Ethanol", "D-Fructose 6-phosphate", "D-Fructose 1,6-bisphosphate", "Formate", "Formate", "D-Fructose", "Fumarate", "Fumarate", "Glyceraldehyde 3-phosphate", "D-Glucose 6-phosphate", "D-Glucose", "L-Glutamine", "L-Glutamine", "L-Glutamate", "L-Glutamate", "Glyoxylate", "H2O H2O", "H2O H2O", "H+", "H+", "Isocitrate", "D-Lactate", "D-Lactate", "L-Malate", "L-Malate", "Nicotinamide adenine dinucleotide", "Nicotinamide adenine dinucleotide - reduced", "Nicotinamide adenine dinucleotide phosphate", "Nicotinamide adenine dinucleotide phosphate - reduced", "Ammonium", "Ammonium", "O2 O2", "O2 O2", "Oxaloacetate", "Phosphoenolpyruvate", "Phosphate", "Phosphate", "Pyruvate", "Pyruvate", "Ubiquinone-8", "Ubiquinol-8", "Alpha-D-Ribose 5-phosphate", "D-Ribulose 5-phosphate", "Sedoheptulose 7-phosphate", "Succinate", "Succinate", "Succinyl-CoA", "D-Xylulose 5-phosphate", "Virtual objective metabolite", "v1", v2", "v3", "v4", "v5", "v6", "v7", "v8", "v9", "v10", "v11", "v12", "v13", "v14", "v15", "v16", "v17", "v18", "v19", "v20", "v21", "v22", "v23", "v24", "v25", "v26", "v27", "v28", "v29", "v30", "v31", "v32", "v33", "v34", "v35", "v36", "v37", "v38", "v39", "v40", "v41", "v42", "v43", "v44", "v45", "v46", "v47", "v48", "v49", "v50", "v51", "v52", "v53", "v54", "v55", "v56", "v57", "v58", "v59", "v60", "v61", "v62", "v63", "v64", "v65", "v66", "v67", "v68", "v69", "v70", "v71", "v72", "v73", "v74", "v75", "v76")
compact <- D[, colSums(D) != 0]
compact_growth <- compact[compact$`Virtual objective metabolite` != 0,]
normalised <- compact_growth / compact_growth$`Virtual objective metabolite`
normalised$glu_efficiency <- normalised$`Virtual objective metabolite` / -normalised$`D-Glucose`
plausible <- normalised %>% filter(glu_efficiency > 0.05 & glu_efficiency < 0.1)


efms <- t(read.csv('/Users/tom/Dropbox/School/MSc Bioinformatics/Internship 1/Playground/e_coli_efms.csv', header = FALSE))
colnames(efms) <- c("Acetaldehyde dehydrogenase (acetylating)", "Acetaldehyde reversible transport", "Acetate kinase", "Aconitase (half-reaction A, Citrate hydro-lyase)", "Aconitase (half-reaction B, Isocitrate hydro-lyase)", "Acetate reversible transport via proton symport", "Adenylate kinase", "2-Oxogluterate dehydrogenase", "2 oxoglutarate reversible transport via symport", "Alcohol dehydrogenase (ethanol)", "ATP maintenance requirement", "ATP synthase (four protons for one ATP)", "Biomass Objective Function with GAM", "CO2 transporter via diffusion", "Citrate synthase", "Cytochrome oxidase bd (ubiquinol-8: 2 protons)", "D lactate transport via proton symport", "Enolase", "Ethanol reversible transport via proton symport", "Acetate exchange", "Acetaldehyde exchange", "2-Oxoglutarate exchange", "CO2 exchange", "Ethanol exchange", "Formate exchange", "D-Fructose exchange", "Fumarate exchange", "D-Glucose exchange", "L-Glutamine exchange", "L-Glutamate exchange", "H+ exchange", "H2O exchange", "D-lactate exchange", "L-Malate exchange", "Ammonia exchange", "O2 exchange", "Phosphate exchange", "Pyruvate exchange", "Succinate exchange", "Fructose-bisphosphate aldolase", "Fructose-bisphosphatase", "Formate transport in via proton symport", "Formate transport via diffusion", "Fumarate reductase", "Fructose transport via PEP:Pyr PTS (f6p generating)", "Fumarase", "Fumarate transport via proton symport (2 H)", "Glucose 6-phosphate dehydrogenase", "Glyceraldehyde-3-phosphate dehydrogenase", "D-glucose transport via PEP:Pyr PTS", "Glutamine synthetase", "L-glutamine transport via ABC system", "Glutamate dehydrogenase (NADP)", "Glutaminase", "Glutamate synthase (NADPH)", "L glutamate transport via proton symport  reversible", "Phosphogluconate dehydrogenase", "H2O transport via diffusion", "Isocitrate dehydrogenase (NADP)", "Isocitrate lyase", "D-lactate dehydrogenase", "Malate synthase", "Malate transport via proton symport (2 H)", "Malate dehydrogenase", "Malic enzyme (NAD)", "Malic enzyme (NADP)", "NADH dehydrogenase (ubiquinone-8 & 3 protons)", "NAD transhydrogenase", "Ammonia reversible transport", "O2 transport  diffusion ", "Pyruvate dehydrogenase", "Phosphofructokinase", "Pyruvate formate lyase", "Glucose-6-phosphate isomerase", "Phosphoglycerate kinase", "6-phosphogluconolactonase", "Phosphoglycerate mutase", "Phosphate reversible transport via symport", "Phosphoenolpyruvate carboxylase", "Phosphoenolpyruvate carboxykinase", "Phosphoenolpyruvate synthase", "Phosphotransacetylase", "Pyruvate kinase", "Pyruvate transport in via proton symport", "Ribulose 5-phosphate 3-epimerase", "Ribose-5-phosphate isomerase", "Succinate transport via proton symport (2 H)", "Succinate transport out via proton antiport", "Succinate dehydrogenase (irreversible)", "Succinyl-CoA synthetase (ADP-forming)", "Transaldolase", "NAD(P) transhydrogenase", "Transketolase", "Transketolase", "Triose-phosphate isomerase")
efms_compact <- efms[, colSums(efms) != 0]
efms_growth <- efms_compact[efms_compact[,13] != 0,]
efms_normalised <- efms_growth / efms_growth[,13]